# Generated by Django 4.0.1 on 2022-02-01 05:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('value', models.CharField(choices=[('Up', 'Ongoing'), ('Down', 'Complete')], max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
